golang-tagged:
  image: golang
  stage: build
  script:
    - go version
    - go test
    - mkdir dist
    - GOOS=windows GOARCH=amd64 go build -ldflags "-X main.versionInformation=`git describe`"
    - mv gcovhtml.exe ./dist/gcovhtml-windows-amd64.exe
    - GOOS=linux GOARCH=amd64 go build -ldflags "-X main.versionInformation=`git describe`"
    - mv gcovhtml ./dist/gcovhtml-linux-amd64
    - GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.versionInformation=`git describe`"
    - mv gcovhtml ./dist/gcovhtml-darwin-amd64
    - GOOS=freebsd GOARCH=amd64 go build -ldflags "-X main.versionInformation=`git describe`"
    - mv gcovhtml ./dist/gcovhtml-freebsd-amd64
    - GOOS=openbsd GOARCH=amd64 go build -ldflags "-X main.versionInformation=`git describe`"
    - mv gcovhtml ./dist/gcovhtml-openbsd-amd64
  artifacts:
    paths:
      - dist/gcovhtml-windows-amd64.exe
      - dist/gcovhtml-linux-amd64
      - dist/gcovhtml-darwin-amd64
      - dist/gcovhtml-freebsd-amd64
      - dist/gcovhtml-openbsd-amd64
  only: 
    - tags

golang-1.12:
  image: golang:1.12
  stage: build
  script:
    - go version
    - go build
    - go test 

golang-1.11:
  image: golang:1.11
  stage: build
  script:
    - go version
    - go build
    - go test
  artifacts:
    paths:
      - gcovhtml
    expire_in: 1 week

golang-1.10:
  image: golang:1.10
  stage: build
  script:
    - go version
    - go build
    - go test

golang-1.9:
  image: golang:1.9
  stage: build
  script:
    - go version
    - go build

test:
  image: golang:1.11
  stage: test
  script:
    - go test -coverprofile=cover.out
    - go tool cover -html=cover.out -o=cover.html
  only:
    - master
  artifacts:
    paths:
      - cover.html

example-gcov-7:
  image: gcc:7
  stage: test
  dependencies:
    - golang-1.11
  script:
    - cd ./example
    - GCOVHTML=../gcovhtml make text
    - GCOVHTML=../gcovhtml make html
  only:
    - master
  artifacts:
    paths:
      - example/*.txt
      - example/*.html
      - example/methods/*.html
    expire_in: 1 week

example-gcov-8:
  image: gcc:8
  stage: test
  dependencies:
    - golang-1.11
  script:
    - cd ./example
    - GCOVHTML=../gcovhtml make text
    - GCOVHTML=../gcovhtml make html
  only:
    - master

pages:
  stage: deploy
  dependencies:
    - test
    - example-gcov-7
  script:
    - mkdir ./public
    - mv cover.html ./public
    - mv example/ ./public
  only:
    - master
  artifacts:
    paths:
      - public
