// Package scov builds a command-line application to process the data files
// generated by gcov, locv, or llvm-cov to generate reports on line code
// coverage, function coverage, and branch coverage.
package main
